#!/bin/env python3

from simple_term_menu import TerminalMenu
import os

def banner():
    print("\n----------------------------------")
    print(" ▄▄▄▄    ██▀███   █    ██ ▄▄▄█████▓▓█████   █████▒▒█████   ██▀███   ▄████▄  ▓█████ ")
    print("▓█████▄ ▓██ ▒ ██▒ ██  ▓██▒▓  ██▒ ▓▒▓█   ▀ ▓██   ▒▒██▒  ██▒▓██ ▒ ██▒▒██▀ ▀█  ▓█   ▀ ")
    print("▒██▒ ▄██▓██ ░▄█ ▒▓██  ▒██░▒ ▓██░ ▒░▒███   ▒████ ░▒██░  ██▒▓██ ░▄█ ▒▒▓█    ▄ ▒███   ")
    print("▒██░█▀  ▒██▀▀█▄  ▓▓█  ░██░░ ▓██▓ ░ ▒▓█  ▄ ░▓█▒  ░▒██   ██░▒██▀▀█▄  ▒▓▓▄ ▄██▒▒▓█  ▄ ")
    print("░▓█  ▀█▓░██▓ ▒██▒▒▒█████▓   ▒██▒ ░ ░▒████▒░▒█░   ░ ████▓▒░░██▓ ▒██▒▒ ▓███▀ ░░▒████▒")
    print("░▒▓███▀▒░ ▒▓ ░▒▓░░▒▓▒ ▒ ▒   ▒ ░░   ░░ ▒░ ░ ▒ ░   ░ ▒░▒░▒░ ░ ▒▓ ░▒▓░░ ░▒ ▒  ░░░ ▒░ ░")
    print("By LeCoqHardi")
    print("-----------------------------------")

def ReturnToMenu():
    os.system("clear")
    banner()
    options = ["Set Target", "Set protocol", "Set Wordlist", "Set session name", "!! Attack !!", "Exit"]
    terminal_menu = TerminalMenu(options)
    menu_entry_index = terminal_menu.show()
    Output = options[menu_entry_index]
    return Output

def main():
    target = "" # Target IP or Hostname
    protocol = "" # Protocol to attack
    wordlist = "" # Wordlist used
    session = "" # session name to bruteforce
    while(1):
        UserChoice = ReturnToMenu()
# -= [TARGET PART] =-
        if (UserChoice == "Set Target"):
            if(target == ""):
                print("Target is currently empty.")
            elif(target != ""):
                print("Current Target : " + target)
            target = input("Target > ")
# -= [PROTOCOL PART] =-
        if (UserChoice == "Set protocol"):
            if(protocol == ""):
                print("Protocol is currently empty.")
            elif(protocol != ""):
                print("Current protocol : " + protocol)
            protocol = input("Protocol > ")
# -= [SESSION NAME PART] =-
        if (UserChoice == "Set session name"):
            if(session == ""):
                print("Session name is currently empty.")
            elif(session != ""):
                print("Current session name : " + session)
            session = input("Session name > ")
# -= [WORDLIST PART] =-
        if (UserChoice == "Set Wordlist"):
            print("WORDLISTS (stored in /usr/share/wordlists) :")
            print("---------------------------")
            os.system("ls /usr/share/wordlists")
            print("---------------------------")
            if(wordlist == ""):
                print("Wordlist is currently empty.")
            elif(wordlist != ""):
                print("Current Wordlist : " + wordlist)
            wordlist = input("Wordlist > ")
            wordlist = "/usr/share/wordlists/" + wordlist
# -= [ATTACK] =-
        if (UserChoice == "!! Attack !!"):
            print("Target is : " + target)
            print("Protocol is : " + protocol)
            print("Wordlist is : " + wordlist)
            print("Session name is : " + session)
            print("Are you sure you want to attack ?")
            options = ["YES I DO !!!", "No i'm a pussy..."]
            terminal_menu = TerminalMenu(options)
            menu_entry_index = terminal_menu.show()
            verif = options[menu_entry_index]
            if(verif == "YES I DO !!!"):
                print("Launching Bruteforce Attack...")
                os.system("sudo hydra -l " + session + " -P " + wordlist + " " + protocol + "://" + target)
                quit()
            elif(verif == "No i'm a pussy..."):
                print("")
# -= [EXIT SCRIPT] =-
        if (UserChoice == "Exit"):
            quit()

if __name__ == "__main__":
    main()